src/api/urls.py
from django.conf.urls import url
from django.urls import path, include, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from rest_framework.urlpatterns import format_suffix_patterns

from api import views

schema_view = get_schema_view(
   openapi.Info(
      title="Memorio API",
      default_version='v1',
      description="Memorio API Documentation",
      contact=openapi.Contact(email="vitdub2@gmail.com"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

app_name = 'api'
urlpatterns = [
    path('users', views.UserList.as_view()),
    path('users/<int:id>', views.UserDetail.as_view()),
    re_path(r'^users/byEmail/(?P<email>[a-zA-Z@.0-9]{0,50})$', views.UserByEmail.as_view()),
    re_path(r'^users/byTelegram/(?P<telegram>[a-zA-Z@.0-9]{0,50})$', views.UserByTelegram.as_view()),
    path('auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', schema_view.with_ui('swagger', cache_timeout=0)),
]

src/main/urls.py
from django.urls import path, re_path

from . import views
from .views import HomeView, AuthView, SignUpView, SettingsView, CalendarListView, CreateEventView, CreateCalendarView, \
    ResetPasswordView, ConfirmedPasswordResetView
from .views.event import EventListView, EventInfoView, EditEventView

app_name = 'main'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('auth', AuthView.as_view(), name='auth'),
    path('logout', views.logout_view, name='logout'),
    path('sign_up', SignUpView.as_view(), name='sign_up'),
    path('reset_password/<str:code>/', ConfirmedPasswordResetView.as_view(), name='reset_confirmed'),
    path('reset', ResetPasswordView.as_view(), name='reset'),
    path('calendars', CalendarListView.as_view(), name='calendars'),
    path('calendars/add', CreateCalendarView.as_view(), name='add_calendar'),
    path('calendars/<int:calendar_id>/', views.calendar_info, name='calendar_info'),
    path('calendars/<int:calendar_id>/add_event', CreateEventView.as_view(), name='add_event'),
    path('calendars/<int:calendar_id>/events/<int:event_id>', EventInfoView.as_view(), name='event_info'),
    path('calendars/<int:calendar_id>/events/<int:event_id>/edit', EditEventView.as_view(), name='event_edit'),
    path('calendars/<int:calendar_id>/events/<int:event_id>/delete', views.delete_event, name='event_delete'),
    path('events', EventListView.as_view(), name='events'),
    path('settings', SettingsView.as_view(), name='settings'),
]

src/memorio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('api/', include('api.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/main/models/base.py
from django.db import models


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

src/main/models/calendar.py
from django.contrib.auth import get_user_model
from django.db import models

from main.models import CalendarUser
from main.models.base import BaseModel
from main.models.event import Event

User = get_user_model()


class Calendar(BaseModel):
    events = models.ManyToManyField(Event, verbose_name='Event', related_name='events', blank=True)
    users = models.ManyToManyField(CalendarUser, verbose_name='Users', related_name='users')
    name = models.CharField(max_length=100, verbose_name='Name')

    class Meta:
        verbose_name = 'calendar'
        verbose_name_plural = 'calendars'

    def __str__(self):
        return self.name

src/main/models/calendar_user.py
from django.contrib.auth import get_user_model
from django.db import models

from main.models.base import BaseModel

from django.utils.translation import gettext_lazy as _

User = get_user_model()


class CalendarUser(BaseModel):
    account = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Account')

    class UserRoles(models.TextChoices):
        EDITOR = 'ED', _('Editor')
        PARTICIPANT = 'PT', _('Participant')

    roles = models.CharField(
        max_length=2,
        choices=UserRoles.choices,
        default=UserRoles.PARTICIPANT,
        verbose_name='Role'
    )

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'user'

    def __str__(self):
        return "%s, %s" % (self.account.__str__(), self.roles)

src/main/models/comment.py
from django.contrib.auth import get_user_model
from django.db import models

from main.models import CalendarUser, File
from main.models.base import BaseModel
from main.models.event import Event

User = get_user_model()


class Comment(BaseModel):
    event = models.OneToOneField(Event, on_delete=models.CASCADE, verbose_name='Event')
    author = models.ForeignKey(CalendarUser, on_delete=models.CASCADE, verbose_name='Author')
    text = models.TextField(verbose_name='Text')
    files = models.ForeignKey(File, on_delete=models.CASCADE, verbose_name='Attachments', blank=True)

    class Meta:
        verbose_name = 'comment'
        verbose_name_plural = 'comments'

    def __str__(self):
        return self.text

src/main/models/event.py
from django.contrib.auth import get_user_model
from django.db import models

from main.models import EventInfo
from main.models import CalendarUser
from main.models.base import BaseModel

User = get_user_model()


class Event(BaseModel):
    created_by = models.ForeignKey(CalendarUser, on_delete=models.CASCADE, verbose_name="Created by")
    event_info = models.OneToOneField(EventInfo, on_delete=models.CASCADE, verbose_name='Event info')

    class Meta:
        verbose_name = 'event'
        verbose_name_plural = 'event'

    def __str__(self):
        return self.event_info.__str__()

src/main/models/file.py
from django.contrib.auth import get_user_model
from django.db import models

from main.models.base import BaseModel

User = get_user_model()


class File(BaseModel):
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Author')
    source = models.FileField(upload_to='files', verbose_name='File')

    class Meta:
        verbose_name = 'file'
        verbose_name_plural = 'files'

    def __str__(self):
        return self.source.name

src/main/models/label.py
from django.contrib.auth import get_user_model
from django.db import models
from main.models import BaseModel

User = get_user_model()


class Label(BaseModel):
    name = models.CharField(max_length=30, verbose_name='Name')
    color = models.CharField(max_length=20, verbose_name='Color', blank=True)

    class Meta:
        verbose_name = 'label'
        verbose_name_plural = 'labels'

    def __str__(self):
        return self.name

src/main/models/notification.py
from django.contrib.auth import get_user_model
from django.db import models

from main.models.base import BaseModel
from main.models.event import Event

User = get_user_model()


class Notification(BaseModel):
    event = models.OneToOneField(Event, on_delete=models.CASCADE, verbose_name='Event')
    message = models.TextField(verbose_name='Message', blank=True)
    last_notify = models.DateTimeField(auto_now_add=True, verbose_name='Last notify date')

    class Meta:
        verbose_name = 'notification'
        verbose_name_plural = 'notifications'

    def __str__(self):
        return self.event.__str__()

src/main/forms.py
from datetime import datetime

from django import forms

from main.models import EventInfo, Label


class AuthForm(forms.Form):
    email = forms.EmailField(label='E-mail', max_length=100, widget=forms.TextInput(attrs={'class': 'uk-input'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'uk-input'}))


class PasswordResetForm(forms.Form):
    email = forms.EmailField(label='E-mail', max_length=100, widget=forms.TextInput(attrs={'class': 'uk-input'}))


class ConfirmedPasswordResetForm(forms.Form):
    password = forms.CharField(label='Password', max_length=100, widget=forms.TextInput(attrs={'class': 'uk-input'}))


class SignUpForm(forms.Form):
    email = forms.EmailField(label='E-mail', max_length=100, widget=forms.TextInput(attrs={'class': 'uk-input'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'uk-input'}))
    name = forms.CharField(label='Name', max_length=20, widget=forms.TextInput(attrs={'class': 'uk-input'}))
    surname = forms.CharField(label='Surname', max_length=20, widget=forms.TextInput(attrs={'class': 'uk-input'}))
    telegram = forms.CharField(label='Telegram', max_length=60, widget=forms.TextInput(attrs={'class': 'uk-input'}))
    photo = forms.FileField(label='Photo', widget=forms.FileInput(attrs={'class': 'uk-input'}))


class CalendarCreateForm(forms.Form):
    name = forms.CharField(label='Calendar name', max_length=50, widget=forms.TextInput(attrs={'class': 'uk-input'}))


class EventForm(forms.Form):
    name = forms.CharField(label='Event name', widget=forms.TextInput(attrs={'class': 'uk-input'}))
    start_time = forms.DateTimeField(label='Start time', initial=datetime.today(), widget=forms.TextInput(attrs={'class': 'uk-input'}))
    end_time = forms.DateTimeField(label='End time', initial=datetime.today(), widget=forms.TextInput(attrs={'class': 'uk-input'}))
    description = forms.CharField(label='Description', required=False, widget=forms.Textarea(attrs={'class': 'uk-input'}))
    place = forms.CharField(label='Place', required=False, widget=forms.TextInput(attrs={'class': 'uk-input'}))
    color = forms.CharField(label='Color', required=False, widget=forms.TextInput(attrs={'class': 'uk-input'}))
    site = forms.URLField(label='Site', required=False, widget=forms.TextInput(attrs={'class': 'uk-input'}))

    REPEAT_INTERVAL = [
        ('NONE', 'None'),
        ('DAY', 'Every day'),
        ('WEEK', 'Every week'),
        ('MONTH', 'Every month'),
        ('YEAR', 'Every year')
    ]

    # repeat_interval = forms.MultipleChoiceField(
    #     required=False,
    #     widget=forms.Select,
    #     choices=REPEAT_INTERVAL,
    #     label='Repeat interval'
    # )

    EVENT_STATUSES = [
        ('NOT_STARTED', 'Not started'),
        ('PROCESS', 'In process'),
        ('COMPLETED', 'Completed'),
        ('DELAYED', 'Delayed')
    ]

    # status = forms.MultipleChoiceField(
    #     required=False,
    #     widget=forms.Select,
    #     choices=EVENT_STATUSES,
    #     label='Status'
    # )

    attachments = forms.FileInput()

    labels = forms.ModelMultipleChoiceField(
        queryset=Label.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
        label='Labels'
    )

src/main/views/calendar.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.views.generic import ListView, FormView

from main import services, models
from main.forms import CalendarCreateForm
from main.mixins import BaseLoginMixin
from main.models import Calendar


class CalendarListView(BaseLoginMixin, ListView):
    model = Calendar
    template_name = 'calendars.html'

    def get_context_data(self, **kwargs):
        req = self.request
        account = req.user
        context = super().get_context_data(**kwargs)
        calendars = services.get_all_calendars_for_user(account.id)
        context['calendars'] = calendars
        return context


@login_required(login_url='/auth')
def calendar_info(req, calendar_id):
    is_allowed = services.is_account_allowed_to_access_calendar(req.user.id, calendar_id)
    if is_allowed:
        calendar = models.Calendar.objects.get(id=calendar_id)
        events = services.get_all_events_by_calendar_id(calendar_id)
        is_editor = services.is_account_editor_for_calendar(calendar.id, req.user.id)
        return render(req, 'calendar_info.html', {
            'events': events,
            'calendar': calendar,
            'is_editor': is_editor
        })
    else:
        return redirect("main:home")


class CreateCalendarView(BaseLoginMixin, FormView):
    template_name = 'calendar_create.html'
    form_class = CalendarCreateForm

    def form_valid(self, form):
        req = self.request
        user = req.user
        editor = services.get_user_with_specified_role(user.id, 'ED')
        if editor is None:
            editor = models.CalendarUser(account=user, roles='ED')
            editor.save()
        new_calendar = models.Calendar(name=req.POST['name'])
        new_calendar.save()
        new_calendar.users.set([editor])
        new_calendar.save()
        return redirect('main:calendars')

src/main/views/event.py
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.views.generic import ListView, FormView

from main import services, models
from main.forms import EventForm
from main.mixins import BaseLoginMixin
from main.models import EventInfo, Event, Calendar


class CreateEventView(BaseLoginMixin, FormView):
    template_name = 'event_create.html'
    form_class = EventForm

    def get_context_data(self, **kwargs):
        calendar_id = self.kwargs['calendar_id']
        context = super().get_context_data(**kwargs)
        calendar = Calendar.objects.get(pk=calendar_id)
        context['calendar'] = calendar
        context['calendar_id'] = calendar_id
        return context

    def form_valid(self, form):
        req = self.request
        account = req.user
        calendar_id = self.kwargs['calendar_id']
        calendar = models.Calendar.objects.get(id=calendar_id)
        editor = services.get_user_with_specified_role(account.id, 'ED')
        event_info = models.EventInfo(
            name=req.POST['name'],
            start_time=req.POST['start_time'],
            end_time=req.POST['end_time'],
            description=req.POST['description'],
            place=req.POST['place'],
            color=req.POST['color'],
            site=req.POST['site'],
            # repeat_interval=req.POST['repeat_interval'],
            # status=req.POST['status'],
        )
        event_info.save()

        event = models.Event(
            event_info=event_info,
            created_by=editor,
        )
        event.save()

        calendar.events.add(event)

        return redirect('main:calendar_info', calendar_id=calendar_id)


class EditEventView(BaseLoginMixin, FormView):
    template_name = 'event_edit.html'
    form_class = EventForm

    def get_context_data(self, **kwargs):
        event_id = self.kwargs['event_id']
        calendar_id = self.kwargs['calendar_id']
        event = Event.objects.get(pk=event_id).event_info
        context = super().get_context_data(**kwargs)
        form = EventForm(initial={
            'name': event.name,
            'start_time': event.start_time,
            'end_time': event.start_time,
            'description': event.description,
            'place': event.place,
            'color': event.color,
            'site': event.site,
            # 'repeat_interval': event.repeat_interval,
            # 'status': event.status
        })
        context['calendar_id'] = calendar_id
        context['event_id'] = event_id
        context['form'] = form
        return context

    def form_valid(self, form):
        req = self.request
        calendar_id = self.kwargs['calendar_id']
        event_id = self.kwargs['event_id']
        event = Event.objects.get(pk=event_id).event_info

        event.name = req.POST['name']
        event.start_time = req['start_time']
        event.end_time = req.POST['end_time']
        event.description = req.POST['description']
        event.place = req.POST['place']
        event.color = req.POST['color']
        event.site = req.POST['site']
        # event.repeat_interval = req.POST['repeat_interval']
        # event.status = req.POST['status']
        event.save()

        return redirect('main:calendars')


class EventListView(BaseLoginMixin, ListView):
    model = EventInfo
    template_name = 'events.html'

    def get_context_data(self, **kwargs):
        req = self.request
        account = req.user
        context = super().get_context_data(**kwargs)
        events = services.get_all_events_by_account(account.id)
        context['events'] = events
        context['now'] = datetime.now()
        return context


class EventInfoView(BaseLoginMixin, ListView):
    template_name = 'event_info.html'
    model = EventInfo

    def get_context_data(self, **kwargs):
        req = self.request
        context = super().get_context_data(**kwargs)
        calendar_id = self.kwargs['calendar_id']
        event_info_id = self.kwargs['event_id']
        event_info = EventInfo.objects.get(pk=event_info_id)
        event = Event.objects.filter(event_info=event_info).first()
        context['calendar_id'] = calendar_id
        context['event_id'] = event.id
        context['event'] = event.event_info
        return context


@login_required(login_url='/auth')
def delete_event(req, calendar_id, event_id):
    calendar = Calendar.objects.get(pk=calendar_id)
    event = Event.objects.get(pk=event_id)
    calendar.events.remove(event)
    event.event_info.delete()
    event.delete()
    calendar.save()
    return redirect('main:calendar_info', calendar_id=calendar_id)

src/main/templates/authentificated.html
{% extends 'base.html' %}
{% block body %}
    {% block content %}{% endblock %}
    <footer>
        <div class="nav-spacer"></div>
        <div class="fab-wrapper">
            <button class="fab-btn" uk-toggle="target: .nav-wrapper; animation: uk-animation-fade">
                <i class="fas fa-bars"></i>
            </button>
        </div>
        <div class="nav-wrapper">
            <div id="inner-nav">
                <a href="{% url 'main:home' %}" class="nav-item">Home</a>
                <a href="{% url 'main:events' %}" class="nav-item">Events</a>
                <a href="{% url 'main:calendars' %}" class="nav-item">Calendars</a>
                <a href="{% url 'main:settings' %}" class="nav-item">Settings</a>
                <a href="{% url 'main:logout' %}" class="nav-item">Logout</a>
            </div>
        </div>
    </footer>
{% endblock %}

src/main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Memorio | {% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="icon" href="{% static 'logo.png' %}">
    <!-- UIkit CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uikit@3.6.18/dist/css/uikit.min.css" />
    <!-- UIkit JS -->
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.6.18/dist/js/uikit.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.6.18/dist/js/uikit-icons.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'base_styles.css' %}">
    <!-- UIkit CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uikit@3.6.18/dist/css/uikit.min.css" />
    <script src="https://kit.fontawesome.com/03414e71d7.js" crossorigin="anonymous"></script>

    <!-- UIkit JS -->
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.6.18/dist/js/uikit.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.6.18/dist/js/uikit-icons.min.js"></script>
</head>
<body>
    <header>
        <h1 class="uk-heading-line uk-text-center">
            <span>
                Memorio
            </span>
        </h1>
    </header>
    {% block body %}{% endblock %}
</body>
</html>

src/main/templates/calendar_create.html
{% extends 'authentificated.html' %}
{% block title %} Create calendar {% endblock %}
{% block content %}
    <h1>Add calendar</h1>
    <form action="{% url 'main:add_calendar' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <button class="uk-button uk-button-primary" type="submit">Create calendar</button>
    </form>
{% endblock %}

src/main/templates/calendar_info.html
{% extends 'authentificated.html' %}
{% block title %} {{ calendar.name }} {% endblock %}
{% block content %}
    <h1>{{ calendar.name }}</h1>
    <div class="col uk-grid-column">
        {% for event in events %}
            <a class="uk-card uk-card-default uk-card-body" style="margin-bottom: 15px" href="{% url 'main:event_info' calendar.id event.id %}">
                {{ event.name }}
            </a>
        {% endfor %}
    </div>
    {% if is_editor %}
        <a class="uk-button uk-button-primary" href="{% url 'main:add_event' calendar.id %}">Add event</a>
    {% endif %}
{% endblock %}

src/main/templates/calendars.html
{% extends 'authentificated.html' %}
{% block title %} Calendars {% endblock %}
{% block content %}
    <h1>Calendars</h1>
    {% for calendar in calendars %}
        <a href="{% url 'main:calendar_info' calendar.id %}" class="nav-item uk-margin uk-card uk-card-default uk-card-body">{{ calendar.name }}</a>
    {% endfor %}
    <a class="uk-button uk-button-primary" href="{% url 'main:add_calendar' %}">Add calendar</a>
{% endblock %}

src/main/templates/confirmed_password_reset.html
{% extends 'base.html' %}
{% block title %} Reset password {% endblock %}
{% block body %}
    <h1>
        Reset password
    </h1>
    <form action="{% url 'main:reset_confirmed' code %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="uk-button uk-margin uk-button-primary">Reset</button>
    </form>
{% endblock %}

src/main/templates/event_create.html
{% extends 'authentificated.html' %}
{% block title %} Create event {% endblock %}
{% block content %}
    <h1>Create event</h1>
    <form action="{% url 'main:add_event' calendar.id %}" method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="uk-button uk-margin uk-button-primary">Create Event</button>
    </form>
{% endblock %}

src/main/templates/event_edit.html
{% extends 'authentificated.html' %}
{% block title %} Edit event {% endblock %}
{% block content %}
    <h1>Edit {{ event.name }}</h1>
    <form action="{% url 'main:event_edit' calendar_id event_id %}" method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="uk-button uk-margin uk-button-primary">
            Save
        </button>
    </form>
{% endblock %}

src/main/templates/event_info.html
{% extends 'authentificated.html' %}
{% block title %} {{ event.name }} page {% endblock %}
{% block content %}
    <h1>{{ event.name }} Page</h1>
    <li style="color: {{ event.color }}">
        <div>{{ event.name }}</div>
        <div>{{ event.description }}</div>
        <div>Starts: {{ event.start_time }}</div>
        <div>Ends: {{ event.end_time }}</div>
        {% if now.date < event.start_time.date %}
        <div class="uk-grid-small uk-child-width-auto" uk-grid uk-countdown="date: {{ event.start_time.date | date }}">
            <div>
                <div class="uk-countdown-number uk-countdown-days"></div>
                <div class="uk-countdown-label uk-margin-small uk-text-center uk-visible@s">Days</div>
            </div>
            <div class="uk-countdown-separator">:</div>
            <div>
                <div class="uk-countdown-number uk-countdown-hours"></div>
                <div class="uk-countdown-label uk-margin-small uk-text-center uk-visible@s">Hours</div>
            </div>
            <div class="uk-countdown-separator">:</div>
            <div>
                <div class="uk-countdown-number uk-countdown-minutes"></div>
                <div class="uk-countdown-label uk-margin-small uk-text-center uk-visible@s">Minutes</div>
            </div>
            <div class="uk-countdown-separator">:</div>
            <div>
                <div class="uk-countdown-number uk-countdown-seconds"></div>
                <div class="uk-countdown-label uk-margin-small uk-text-center uk-visible@s">Seconds</div>
            </div>
        </div>
        {% endif %}
    </li>
    <a class="uk-button uk-button-primary" href="{% url 'main:event_edit' calendar_id event_id %}">
        Edit this event
    </a>
    <a class="uk-button uk-button-danger" href="{% url 'main:event_delete' calendar_id event_id %}">
        Delete this event
    </a>
{% endblock %}

src/main/templates/events.html
{% extends 'authentificated.html' %}
{% block title %} Events page {% endblock %}
{% block content %}
    <h1>Events Page</h1>
    {% for event in events %}
        <li style="color: {{ event.color }}">
            <div>{{ event.name }}</div>
            <div>{{ event.description }}</div>
            <div>Starts: {{ event.start_time }}</div>
            <div>Ends: {{ event.end_time }}</div>
            {% if now.date < event.start_time.date %}
            <div class="uk-grid-small uk-child-width-auto" uk-grid uk-countdown="date: {{ event.start_time.date | date }}">
                <div>
                    <div class="uk-countdown-number uk-countdown-days"></div>
                    <div class="uk-countdown-label uk-margin-small uk-text-center uk-visible@s">Days</div>
                </div>
                <div class="uk-countdown-separator">:</div>
                <div>
                    <div class="uk-countdown-number uk-countdown-hours"></div>
                    <div class="uk-countdown-label uk-margin-small uk-text-center uk-visible@s">Hours</div>
                </div>
                <div class="uk-countdown-separator">:</div>
                <div>
                    <div class="uk-countdown-number uk-countdown-minutes"></div>
                    <div class="uk-countdown-label uk-margin-small uk-text-center uk-visible@s">Minutes</div>
                </div>
                <div class="uk-countdown-separator">:</div>
                <div>
                    <div class="uk-countdown-number uk-countdown-seconds"></div>
                    <div class="uk-countdown-label uk-margin-small uk-text-center uk-visible@s">Seconds</div>
                </div>
            </div>
            {% endif %}
        </li>
    {% endfor %}
{% endblock %}

src/main/templates/main.html
{% extends 'authentificated.html' %}
{% block title %} Main page {% endblock %}
{% block content %}
    <h1>Hello, {{ fullname }}</h1>
    <div class="ava">
        {% if avatar.url %}
            <img src="{{ avatar.url }}">
        {% endif %}
    </div>
    <div class="col uk-grid-column">
        <a href="{% url 'main:events' %}" class="nav-item uk-card uk-card-default uk-card-body">Events</a>
        <a href="{% url 'main:calendars' %}" class="nav-item uk-card uk-card-default uk-card-body">Calendars</a>
        <a href="{% url 'main:settings' %}" class="nav-item uk-card uk-card-default uk-card-body">Settings</a>
        <a href="{% url 'main:logout' %}" class="nav-item uk-card uk-card-default uk-card-body">Logout</a>
    </div>
{% endblock %}

src/main/templates/password_reset.html
{% extends 'base.html' %}
{% block title %} Reset password {% endblock %}
{% block body %}
    <h1>
        Reset password
    </h1>
    <form action="{% url 'main:reset' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="uk-button uk-margin uk-button-primary">Reset</button>
    </form>

    <a class="uk-button uk-margin uk-button-default" href="{% url 'main:auth' %}">Auth</a>
    <a class="uk-button uk-margin uk-button-default" href="{% url 'main:sign_up' %}">Sign up</a>
{% endblock %}

src/main/templates/settings.html
{% extends 'authentificated.html' %}
{% block title %} Settings page {% endblock %}
{% block content %}
    <h1>Settings Page</h1>
{% endblock %}

src/main/templates/sign_up.html
{% extends 'base.html' %}
{% block title %} Sign up {% endblock %}
{% block body %}
    <h1>
        Sign up page
    </h1>
    <form action="{% url 'main:sign_up' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="uk-button uk-margin uk-button-primary">Sign up</button>
    </form>

    <a class="uk-button uk-margin uk-button-default" href="{% url 'main:auth' %}">Auth</a>
{% endblock %}